# change the followings to match your GitHub username and repo name
baseurl: "/" # the name of your github repo
url: "https://lewisrye.tech" # the url of your github pages

# site information used in page title, meta data etc.
title: "Lewis Rye"
description: Portfolio Website

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Lewis Rye
author-bio: BSc Computer Science Student  # change to false to hide
author-image: pfp.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Projects
  permalink: projects
- text: Contact
  permalink: contact

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/lewisrye
linkedin: https://linkedin.com/in/lewis-rye/
medium: false
google-scholar: false
email: lewis@lewisrye.tech

# footer information
footer-msg: "created with Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
